In [1]:
import pandas as pd

In [2]:
# اعمل DataFrame بسيط
data = {
    'Name': ['Mohamed', 'Ahmed', 'Ali'],
    'Age': [20, 22, 25],
    'City': ['Istanbul', 'Cairo', 'Ankara']
}

df = pd.DataFrame(data)
df

      Name  Age      City
0  Mohamed   20  Istanbul
1    Ahmed   22     Cairo
2      Ali   25    Ankara

In [3]:
df.head()

      Name  Age      City
0  Mohamed   20  Istanbul
1    Ahmed   22     Cairo
2      Ali   25    Ankara

In [4]:
df.shape

(3, 3)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [6]:
df.describe()

             Age
count   3.000000
mean   22.333333
std     2.516611
min    20.000000
25%    21.000000
50%    22.000000
75%    23.500000
max    25.000000

In [10]:
df['Name']

0    Mohamed
1      Ahmed
2        Ali
Name: Name, dtype: str

In [13]:
df.loc[0]

Name     Mohamed
Age           20
City    Istanbul
Name: 0, dtype: object