In [58]:
import pandas as pd

In [59]:
people = {
    "first":["Mohamed", "Ramy", "Aya"],
    "last" :["Ashraf", "Ahmed", "Ali"], 
    "email":["mohamedashraf1@gmail.com", "ramyahmed1@gmail.com", "ayaali@gmail.com"] ,
}

In [60]:
df = pd.DataFrame(people)
df

     first    last                     email
0  Mohamed  Ashraf  mohamedashraf1@gmail.com
1     Ramy   Ahmed      ramyahmed1@gmail.com
2      Aya     Ali          ayaali@gmail.com

In [61]:
df.columns =["first_name", "last_name", "email"]

In [62]:
df

  first_name last_name                     email
0    Mohamed    Ashraf  mohamedashraf1@gmail.com
1       Ramy     Ahmed      ramyahmed1@gmail.com
2        Aya       Ali          ayaali@gmail.com

In [63]:
df.columns=df.columns.str.replace("_", " ")

In [64]:
df

  first name last name                     email
0    Mohamed    Ashraf  mohamedashraf1@gmail.com
1       Ramy     Ahmed      ramyahmed1@gmail.com
2        Aya       Ali          ayaali@gmail.com

In [65]:
df.columns = [x.lower() for x in df.columns]

In [66]:
df

  first name last name                     email
0    Mohamed    Ashraf  mohamedashraf1@gmail.com
1       Ramy     Ahmed      ramyahmed1@gmail.com
2        Aya       Ali          ayaali@gmail.com

In [67]:
df.rename(columns={"first name":"first"},inplace=True)

In [68]:
df

     first last name                     email
0  Mohamed    Ashraf  mohamedashraf1@gmail.com
1     Ramy     Ahmed      ramyahmed1@gmail.com
2      Aya       Ali          ayaali@gmail.com

In [69]:
df["email"]=df["email"].str.upper()

In [70]:
df

     first last name                     email
0  Mohamed    Ashraf  MOHAMEDASHRAF1@GMAIL.COM
1     Ramy     Ahmed      RAMYAHMED1@GMAIL.COM
2      Aya       Ali          AYAALI@GMAIL.COM

In [71]:
df.loc[2]= ("habeba","ashraf","habebaashraf@gmail.com")

In [72]:
df

     first last name                     email
0  Mohamed    Ashraf  MOHAMEDASHRAF1@GMAIL.COM
1     Ramy     Ahmed      RAMYAHMED1@GMAIL.COM
2   habeba    ashraf    habebaashraf@gmail.com

In [73]:
df.loc[2]= df.loc[2].str.upper()

In [74]:
df

     first last name                     email
0  Mohamed    Ashraf  MOHAMEDASHRAF1@GMAIL.COM
1     Ramy     Ahmed      RAMYAHMED1@GMAIL.COM
2   HABEBA    ASHRAF    HABEBAASHRAF@GMAIL.COM

In [75]:
df.loc[2]=df.loc[2].str.lower()

In [76]:
df

     first last name                     email
0  Mohamed    Ashraf  MOHAMEDASHRAF1@GMAIL.COM
1     Ramy     Ahmed      RAMYAHMED1@GMAIL.COM
2   habeba    ashraf    habebaashraf@gmail.com

In [77]:
df["email"]=df["email"].str.upper()

In [78]:
df

     first last name                     email
0  Mohamed    Ashraf  MOHAMEDASHRAF1@GMAIL.COM
1     Ramy     Ahmed      RAMYAHMED1@GMAIL.COM
2   habeba    ashraf    HABEBAASHRAF@GMAIL.COM

In [79]:
df.columns=df.columns.str.replace(" ","_")

In [80]:
df

     first last_name                     email
0  Mohamed    Ashraf  MOHAMEDASHRAF1@GMAIL.COM
1     Ramy     Ahmed      RAMYAHMED1@GMAIL.COM
2   habeba    ashraf    HABEBAASHRAF@GMAIL.COM

In [81]:
df.rename(columns={"first":"first_name"},inplace=True)

In [82]:
df.loc[2,"first_name"]="Habeba"

In [83]:
df

  first_name last_name                     email
0    Mohamed    Ashraf  MOHAMEDASHRAF1@GMAIL.COM
1       Ramy     Ahmed      RAMYAHMED1@GMAIL.COM
2     Habeba    ashraf    HABEBAASHRAF@GMAIL.COM

In [84]:
df["email"].apply(len)

0    24
1    20
2    22
Name: email, dtype: int64

In [85]:
def update_email(email):
    return email.lower()

In [86]:
df["email"]=df["email"].apply(update_email)

In [87]:
df

  first_name last_name                     email
0    Mohamed    Ashraf  mohamedashraf1@gmail.com
1       Ramy     Ahmed      ramyahmed1@gmail.com
2     Habeba    ashraf    habebaashraf@gmail.com

In [88]:
df["email"]=df["email"].apply(lambda x: x.upper())

In [89]:
df

  first_name last_name                     email
0    Mohamed    Ashraf  MOHAMEDASHRAF1@GMAIL.COM
1       Ramy     Ahmed      RAMYAHMED1@GMAIL.COM
2     Habeba    ashraf    HABEBAASHRAF@GMAIL.COM